### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by urbanisierung** [flethy/flethy#415]
# Roadmap

## 2022-11-14

- [ ] Integrations
  - [x] https://metalpriceapi.com/
  - [ ] https://strapi.io/
- [ ] Console
  - [x] POC Monaco Editor: https://github.com/suren-atoyan/monaco-react

---

## 2022-12-05

- [ ] Integrations:
  - [ ] https://buttercms.com/docs/api/

## 2022-11-28

- [ ] Integrations:
  - [ ] https://developer.vimeo.com/api/reference
  - [ ] https://api.thenounproject.com/explorer
  - [ ] https://docs.mail.tm/
  - [ ] https://boggio-analytics.com/fp-api/
  - [ ] https://boggio-analytics.com/fp-api/
  - [ ] https://developer.uber.com/docs/riders/ride-requests/tutorials/api/introduction
  - [ ] https://cronhub.io/

## 2022-11-21

- [ ] Integrations:
  - [ ] https://docs.warrant.dev/objecttypes/create-an-object-type/
  - [ ] https://beew.io/api
  - [ ] https://docs.sheetson.com/getting-started/
  - [ ] https://appwrite.io/docs/client/account
  - [ ] https://www.wordsapi.com/
  - [ ] https://mailboxlayer.com/
  - [ ] https://pprathameshmore.github.io/QuoteGarden/
- [ ] Landing Page:
  - [ ] Setup generation of use cases
- [ ] Use Cases
  - [ ] Auth0: Create a user
  - [ ] Auth0: Update App Metadata

---

### Done

**Comment by urbanisierung** [comment]
- add flow response

**Comment by urbanisierung** [comment]
replaced with issues per week
